version: "3.9"
services:
  node-fastify:
    image: node-container
    container_name: node-api
    build:
      context: .
    volumes:
      - ./:/app
      - /app/node_modules
    tty: true
    ports:
      - "8001:8000"
